apiVersion: v1
name: acm-chart
description: A Helm chart for the ACK service controller for AWS Certificate Manager (ACM)
version: 1.0.5
appVersion: 1.0.5
home: https://github.com/aws-controllers-k8s/acm-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/acm-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: ACM Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/acm-maintainer
keywords:
  - aws
  - kubernetes
  - acm
